### ISSUE TITLE
dynamic inventory not working

### ISSUE THREAD

**Issue by tamsky** [dominis/ansible-shell#40]
This doesn't work as I expected:
```
# ansible-shell -i inventories/ec2/
Traceback (most recent call last):
  File "/usr/local/bin/ansible-shell", line 33, in <module>
    class AnsibleShell(cmd.Cmd):
  File "/usr/local/bin/ansible-shell", line 35, in AnsibleShell
    ansible = ansible.runner.Runner()
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 178, in __init__
    self.inventory        = utils.default(inventory, lambda: ansible.inventory.Inventory(host_list))
  File "/Library/Python/2.7/site-packages/ansible/utils/__init__.py", line 833, in default
    return function()
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 178, in <lambda>
    self.inventory        = utils.default(inventory, lambda: ansible.inventory.Inventory(host_list))
  File "/Library/Python/2.7/site-packages/ansible/inventory/__init__.py", line 139, in __init__
    raise errors.AnsibleError("Unable to find an inventory file, specify one with -i ?")
ansible.errors.AnsibleError: Unable to find an inventory file, specify one with -i ?

Same error for:
# ansible-shell -i ./<directory>/ec2.py
```

These inventory args do work with plain `ansible`:
```
# ansible '*' -i ./inventories/ec2 --list-hosts | wc -l
     124
# ansible '*' -i ./inventories/ec2/ec2.py --list-hosts | wc -l
     124
```

**Comment by tamsky** [comment]
N/m this was a problem with the version installed by using:
```
$ pip install ansible-shell
```
