### ISSUE TITLE
Cannot be used after installation

### ISSUE THREAD

**Issue by zhaolx01** [dominis/ansible-shell#53]
```
root@lixia:~/soft/ansible-shell# ansible-shell
Traceback (most recent call last):
  File "/usr/local/bin/ansible-shell", line 4, in <module>
    __import__('pkg_resources').run_script('ansible-shell==0.0.5', 'ansible-shell')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ansible_shell-0.0.5-py2.7.egg/EGG-INFO/scripts/ansible-shell", line 36, in <module>
    
ImportError: No module named runner
root@lixia:~/soft/ansible-shell# 
```

**Comment by iambocai** [comment]
As of Ansible 2.1 ansible-shell is part of the official ansible release: https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/console.py

**Comment by Pysis868** [comment]
Usage: https://github.com/dominis/ansible-shell/issues/52#issuecomment-300336252
